# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmdrunner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x63mdrunner.proto\x12\tcmdrunner"+\n\nRunRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t"-\n\x0c\x43ommandReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07message\x18\x02 \x01(\t2\x94\x01\n\x06Runner\x12>\n\nRunCommand\x12\x15.cmdrunner.RunRequest\x1a\x17.cmdrunner.CommandReply"\x00\x12J\n\x12RunCommandOneByOne\x12\x15.cmdrunner.RunRequest\x1a\x17.cmdrunner.CommandReply"\x00(\x01\x30\x01\x62\x06proto3'
)


_RUNREQUEST = DESCRIPTOR.message_types_by_name["RunRequest"]
_COMMANDREPLY = DESCRIPTOR.message_types_by_name["CommandReply"]
RunRequest = _reflection.GeneratedProtocolMessageType(
    "RunRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _RUNREQUEST,
        "__module__": "cmdrunner_pb2"
        # @@protoc_insertion_point(class_scope:cmdrunner.RunRequest)
    },
)
_sym_db.RegisterMessage(RunRequest)

CommandReply = _reflection.GeneratedProtocolMessageType(
    "CommandReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _COMMANDREPLY,
        "__module__": "cmdrunner_pb2"
        # @@protoc_insertion_point(class_scope:cmdrunner.CommandReply)
    },
)
_sym_db.RegisterMessage(CommandReply)

_RUNNER = DESCRIPTOR.services_by_name["Runner"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _RUNREQUEST._serialized_start = 30
    _RUNREQUEST._serialized_end = 73
    _COMMANDREPLY._serialized_start = 75
    _COMMANDREPLY._serialized_end = 120
    _RUNNER._serialized_start = 123
    _RUNNER._serialized_end = 271
# @@protoc_insertion_point(module_scope)
